client:
  url: "https://www.wildberries.ru/"
  request_text: "пальто из натуральной шерсти"

excel:
  columns:
    - Ссылка на товар
    - Артикул
    - Название
    - Цена
    - Описание
    - Ссылки на изображения через запятую
    - Все характеристики с сохранением их структуры
    - Название селлера
    - Ссылка на селлера
    - Размеры товара через запятую 
    - Остатки по товару (число)
    - Рейтинг
    - Количество отзывов


excel_filter:
  raiting: 4.5
  cost: 10000
  made_in: "Россия"